a

diff --git a/.github/workflows/ci-test.yaml b/.github/workflows/ci-test.yaml
--- a/.github/workflows/ci-test.yaml
+++ b/.github/workflows/ci-test.yaml
@@ -108,10 +108,15 @@ jobs:
 
   package-snapd-rpm:
     runs-on: ubuntu-latest
+    name: Package ${{ matrix.system }}
     steps:
     - name: Step 1
       run: |
         if [ "${{ matrix.system }}" = "opensuse" ]; then
+          echo "result=failed" >> $GITHUB_OUTPUT
+          exit 1
+        fi  
+        if [ "${{ matrix.system }}" = "centos" ]; then
           echo "result=failed" >> $GITHUB_OUTPUT
           exit 1
         fi  
@@ -123,11 +128,11 @@ jobs:
         system: 
           - opensuse
           - fedora
+          - centos
 
   
   package-snapd-arch:
     name: Package arch
-    id: arch-package
     runs-on: ubuntu-latest
     steps:
     - name: Step 1
@@ -163,8 +168,9 @@ jobs:
         if grep -q "failure" <<<$needs_results; then
           # sleep to make sure that when we query the api in the next loop, it has had time to update
           sleep 1
-          # jobs_results=$(gh api repos/{owner}/{repo}/actions/runs/$GITHUB_RUN_ID/jobs)
-          gh api repos/{owner}/{repo}/actions/runs/$GITHUB_RUN_ID/jobs | jq .
+          jobs_results=$(gh api repos/{owner}/{repo}/actions/runs/$GITHUB_RUN_ID/jobs)
+          failed=$(jq -r '.jobs[] | select(.name | startswith("Package")) | select(.conclusion != "success") | "\(.name)"' <<<"$jobs_results")
+          echo "failed packaging for systems $failed"
         fi
 
         echo "Summary:"
