a

diff --git a/.github/workflows/weekly-feature-tagging.yaml b/.github/workflows/weekly-feature-tagging.yaml
--- a/.github/workflows/weekly-feature-tagging.yaml
+++ b/.github/workflows/weekly-feature-tagging.yaml
@@ -77,71 +77,74 @@ jobs:
           echo "non-fundamental-systems=$non_fundamental_systems" >> $GITHUB_OUTPUT
           echo "nested-systems=$nested_systems" >> $GITHUB_OUTPUT
 
-  tag-features-fundamental:
-    uses: ./.github/workflows/spread-tests.yaml
-    needs: [set-inputs, read-systems]
-    name: "spread ${{ matrix.group }}"
-    if: needs.read-systems.outputs.fundamental-systems != ''
-    with:
-      runs-on: '["self-hosted", "spread-enabled"]'
-      group: ${{ matrix.group }}
-      backend: ${{ matrix.backend }}
-      systems: ${{ matrix.systems }}  
-      tasks: ${{ matrix.tasks }}
-      rules: ${{ matrix.rules }}
-      is-fundamental: true
-      use-snapd-snap-from-master: true
-      spread-env: "SPREAD_TAG_FEATURES=1"
-      upload-artifacts: true
-      skip-tests: ${{ needs.set-inputs.outputs.skip-tests }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.read-systems.outputs.fundamental-systems) }}
+      - name: fail
+        run: exit 1
 
-  tag-features-non-fundamental:
-    uses: ./.github/workflows/spread-tests.yaml
-    needs: [set-inputs, read-systems]
-    if: needs.read-systems.outputs.non-fundamental-systems != ''
-    name: "spread ${{ matrix.group }}"
-    with:
-      runs-on: '["self-hosted", "spread-enabled"]'
-      group: ${{ matrix.group }}
-      backend: ${{ matrix.backend }}
-      systems: ${{ matrix.systems }}  
-      tasks: ${{ matrix.tasks }}
-      rules: ${{ matrix.rules }}
-      use-snapd-snap-from-master: true
-      spread-env: "SPREAD_TAG_FEATURES=1"
-      upload-artifacts: true
-      skip-tests: ${{ needs.set-inputs.outputs.skip-tests }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.read-systems.outputs.non-fundamental-systems) }}
+  # tag-features-fundamental:
+  #   uses: ./.github/workflows/spread-tests.yaml
+  #   needs: [set-inputs, read-systems]
+  #   name: "spread ${{ matrix.group }}"
+  #   if: needs.read-systems.outputs.fundamental-systems != ''
+  #   with:
+  #     runs-on: '["self-hosted", "spread-enabled"]'
+  #     group: ${{ matrix.group }}
+  #     backend: ${{ matrix.backend }}
+  #     systems: ${{ matrix.systems }}  
+  #     tasks: ${{ matrix.tasks }}
+  #     rules: ${{ matrix.rules }}
+  #     is-fundamental: true
+  #     use-snapd-snap-from-master: true
+  #     spread-env: "SPREAD_TAG_FEATURES=1"
+  #     upload-artifacts: true
+  #     skip-tests: ${{ needs.set-inputs.outputs.skip-tests }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.read-systems.outputs.fundamental-systems) }}
 
-  tag-features-nested:
-    uses: ./.github/workflows/spread-tests.yaml
-    needs: [set-inputs, read-systems]
-    if: needs.read-systems.outputs.nested-systems != ''
-    name: "spread ${{ matrix.group }}"
-    with:
-      runs-on: '["self-hosted", "spread-enabled"]'
-      group: ${{ matrix.group }}
-      backend: ${{ matrix.backend }}
-      systems: ${{ matrix.systems }}  
-      tasks: ${{ matrix.tasks }}
-      rules: ${{ matrix.rules }}
-      use-snapd-snap-from-master: true
-      spread-env: "SPREAD_TAG_FEATURES=1"
-      upload-artifacts: true
-      skip-tests: ${{ needs.set-inputs.outputs.skip-tests }}
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.read-systems.outputs.nested-systems) }}
+  # tag-features-non-fundamental:
+  #   uses: ./.github/workflows/spread-tests.yaml
+  #   needs: [set-inputs, read-systems]
+  #   if: needs.read-systems.outputs.non-fundamental-systems != ''
+  #   name: "spread ${{ matrix.group }}"
+  #   with:
+  #     runs-on: '["self-hosted", "spread-enabled"]'
+  #     group: ${{ matrix.group }}
+  #     backend: ${{ matrix.backend }}
+  #     systems: ${{ matrix.systems }}  
+  #     tasks: ${{ matrix.tasks }}
+  #     rules: ${{ matrix.rules }}
+  #     use-snapd-snap-from-master: true
+  #     spread-env: "SPREAD_TAG_FEATURES=1"
+  #     upload-artifacts: true
+  #     skip-tests: ${{ needs.set-inputs.outputs.skip-tests }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.read-systems.outputs.non-fundamental-systems) }}
+
+  # tag-features-nested:
+  #   uses: ./.github/workflows/spread-tests.yaml
+  #   needs: [set-inputs, read-systems]
+  #   if: needs.read-systems.outputs.nested-systems != ''
+  #   name: "spread ${{ matrix.group }}"
+  #   with:
+  #     runs-on: '["self-hosted", "spread-enabled"]'
+  #     group: ${{ matrix.group }}
+  #     backend: ${{ matrix.backend }}
+  #     systems: ${{ matrix.systems }}  
+  #     tasks: ${{ matrix.tasks }}
+  #     rules: ${{ matrix.rules }}
+  #     use-snapd-snap-from-master: true
+  #     spread-env: "SPREAD_TAG_FEATURES=1"
+  #     upload-artifacts: true
+  #     skip-tests: ${{ needs.set-inputs.outputs.skip-tests }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.read-systems.outputs.nested-systems) }}
 
   re-run:
     permissions:
       actions: write
-    needs: [set-inputs, tag-features-fundamental, tag-features-non-fundamental, tag-features-nested]
+    needs: [set-inputs, read-systems]
     # If the spread tests ended in failure, rerun the workflow up to maximum-reruns times
     if: failure() && fromJSON(github.run_attempt) <= fromJSON(needs.set-inputs.outputs.maximum-reruns)
     runs-on: ubuntu-latest
@@ -167,84 +170,84 @@ jobs:
           name: "all-features"
           path: "all-features.json"
 
-  create-reports:
-    needs: [set-inputs, tag-features-fundamental, tag-features-non-fundamental, tag-features-nested, get-all-features]
-    runs-on: ["self-hosted", "spread-enabled"]
-    if: |
-      (always() && (needs.tag-features-fundamental.result == 'success' || needs.tag-features-fundamental.result == 'skipped')
-      && (needs.tag-features-non-fundamental.result == 'success' || needs.tag-features-non-fundamental.result == 'skipped')
-      && (needs.tag-features-nested.result == 'success' || needs.tag-features-nested.result == 'skipped')) 
-      || fromJSON(github.run_attempt) > fromJSON(needs.set-inputs.outputs.maximum-reruns)
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # create-reports:
+  #   needs: [set-inputs, tag-features-fundamental, tag-features-non-fundamental, tag-features-nested, get-all-features]
+  #   runs-on: ["self-hosted", "spread-enabled"]
+  #   if: |
+  #     (always() && (needs.tag-features-fundamental.result == 'success' || needs.tag-features-fundamental.result == 'skipped')
+  #     && (needs.tag-features-non-fundamental.result == 'success' || needs.tag-features-non-fundamental.result == 'skipped')
+  #     && (needs.tag-features-nested.result == 'success' || needs.tag-features-nested.result == 'skipped')) 
+  #     || fromJSON(github.run_attempt) > fromJSON(needs.set-inputs.outputs.maximum-reruns)
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Get generated data
-        uses: actions/download-artifact@v4
-        with:
-          path: feature-tags-artifacts
-          pattern: spread-artifacts-*
-          merge-multiple: true
+  #     - name: Get generated data
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         path: feature-tags-artifacts
+  #         pattern: spread-artifacts-*
+  #         merge-multiple: true
 
-      - name: Get all features
-        uses: actions/download-artifact@v4
-        with:
-          name: all-features
+  #     - name: Get all features
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: all-features
 
-      - name: Create feature tags
-        run: |
-          featdir="extracted-tags"
-          mkdir -p "$featdir"
-          composedir="composed-tags"
-          mkdir -p "$composedir"
-          IFS=',' read -ra features <<< "${{ needs.set-inputs.outputs.features }}"
-          for file in "feature-tags-artifacts"/*; do
-            mkdir working
-            tar -xzf "$file" -C working
-            for dir in "working/spread-artifacts/feature-tags"/*/; do
-              if [ -f "${dir}/journal.txt" ] && [ -f "${dir}/state.json" ]; then
-                ./tests/utils/features/featextractor.py \
-                  -f "${features[@]}" \
-                  --journal "${dir}/journal.txt" \
-                  --state "${dir}/state.json" \
-                  --output "$featdir/$(basename ${dir})"
-              elif [ -f "${dir}/journal.txt" ] && [ ! -f "${dir}/state.json" ]; then
-                ./tests/utils/features/featextractor.py \
-                  -f "${features[@]}" \
-                  --journal "${dir}/journal.txt" \
-                  --output "$featdir/$(basename ${dir})"
-              elif [ ! -f "${dir}/journal.txt" ]; then
-                echo "No journal.txt present in $dir"
-                exit 1
-              fi
-            done
-            ./tests/utils/features/featcomposer.py \
-                --dir "$featdir" \
-                --output "$composedir" \
-                --failed-tests "working/spread-artifacts/failed-tests.txt" \
-                --run-attempt "$(cat "working/spread-artifacts/run-attempt.txt")" \
-                --env-variables "$(cat "working/spread-artifacts/env-variables.txt")"
-            rm -r working
-          done
-          ./tests/utils/features/featcomposer.py \
-            --dir "$composedir" \
-            --output "final-feature-tags" \
-            --replace-old-runs
+  #     - name: Create feature tags
+  #       run: |
+  #         featdir="extracted-tags"
+  #         mkdir -p "$featdir"
+  #         composedir="composed-tags"
+  #         mkdir -p "$composedir"
+  #         IFS=',' read -ra features <<< "${{ needs.set-inputs.outputs.features }}"
+  #         for file in "feature-tags-artifacts"/*; do
+  #           mkdir working
+  #           tar -xzf "$file" -C working
+  #           for dir in "working/spread-artifacts/feature-tags"/*/; do
+  #             if [ -f "${dir}/journal.txt" ] && [ -f "${dir}/state.json" ]; then
+  #               ./tests/utils/features/featextractor.py \
+  #                 -f "${features[@]}" \
+  #                 --journal "${dir}/journal.txt" \
+  #                 --state "${dir}/state.json" \
+  #                 --output "$featdir/$(basename ${dir})"
+  #             elif [ -f "${dir}/journal.txt" ] && [ ! -f "${dir}/state.json" ]; then
+  #               ./tests/utils/features/featextractor.py \
+  #                 -f "${features[@]}" \
+  #                 --journal "${dir}/journal.txt" \
+  #                 --output "$featdir/$(basename ${dir})"
+  #             elif [ ! -f "${dir}/journal.txt" ]; then
+  #               echo "No journal.txt present in $dir"
+  #               exit 1
+  #             fi
+  #           done
+  #           ./tests/utils/features/featcomposer.py \
+  #               --dir "$featdir" \
+  #               --output "$composedir" \
+  #               --failed-tests "working/spread-artifacts/failed-tests.txt" \
+  #               --run-attempt "$(cat "working/spread-artifacts/run-attempt.txt")" \
+  #               --env-variables "$(cat "working/spread-artifacts/env-variables.txt")"
+  #           rm -r working
+  #         done
+  #         ./tests/utils/features/featcomposer.py \
+  #           --dir "$composedir" \
+  #           --output "final-feature-tags" \
+  #           --replace-old-runs
 
-          ./tests/utils/features/feattranslator.py -f all-features.json -o final-feature-tags/all-features.json
+  #         ./tests/utils/features/feattranslator.py -f all-features.json -o final-feature-tags/all-features.json
 
-          tar -czf "final-feature-tags.tar.gz" "final-feature-tags"
+  #         tar -czf "final-feature-tags.tar.gz" "final-feature-tags"
 
-      - name: Upload results to mongo
-        env: 
-          MONGO_USER: ${{ secrets.MONGO_USER }}
-          MONGO_PASSWORD: ${{ secrets.MONGO_PASS }}
-          MONGO_HOST: ${{ secrets.MONGO_HOST }}
-          MONGO_PORT: ${{ secrets.MONGO_PORT }}
-        run: ./tests/utils/features/mongo_upload.py --dir "final-feature-tags" --verbose
+  #     - name: Upload results to mongo
+  #       env: 
+  #         MONGO_USER: ${{ secrets.MONGO_USER }}
+  #         MONGO_PASSWORD: ${{ secrets.MONGO_PASS }}
+  #         MONGO_HOST: ${{ secrets.MONGO_HOST }}
+  #         MONGO_PORT: ${{ secrets.MONGO_PORT }}
+  #       run: ./tests/utils/features/mongo_upload.py --dir "final-feature-tags" --verbose
       
-      - name: Upload feature data
-        uses: actions/upload-artifact@v4
-        with:
-          name: "feature-tags"
-          path: "final-feature-tags.tar.gz"
+  #     - name: Upload feature data
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: "feature-tags"
+  #         path: "final-feature-tags.tar.gz"
